# Generated by Django 4.1.7 on 2023-02-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_credentials_remove_storageinsert_file_path_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
